### ISSUE TITLE
Is Animation wb ready for FreeCAD v1.0 ?

### ISSUE THREAD

**Issue by luzpaz** [QuentinTournier40/AnimationFreeCAD#16]
* https://github.com/FreeCAD/Addons/issues/13

**Comment by luzpaz** [comment]
bump @QuentinTournier40

**Comment by QuentinTournier40** [comment]
Hey, just tested.
LGTM

**Comment by luzpaz** [comment]
Tested on what version? Please add full [About](https://wiki.freecad.org/About) info (for posterity)

**Comment by QuentinTournier40** [comment]
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 1.0.0RC2.38806 (Git)
Build type: Release
Branch: (HEAD detached at 1.0rc2)
Hash: 3d63fc6c2f665a8d5e6468845a419bcac80756c7
Python 3.11.9, Qt 5.15.13, Coin 4.0.3, Vtk 9.2.6, OCC 7.7.2
Locale: English/United Kingdom (en_GB)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
Installed mods: 
  * AnimationFreeCAD 1.0.0
