### ISSUE TITLE
FreeCAD colors switch dark when PyFlow start

### ISSUE THREAD

**Issue by FlachyJoe** [QuentinTournier40/AnimationFreeCAD#7]
Initial GUI:
![Capture d’écran_2022-04-12_21-55-31](https://user-images.githubusercontent.com/10371513/163043216-4b835501-4a16-446b-937e-20d5234bc63f.png)
When PyFlow is launched:
![Capture d’écran_2022-04-12_21-56-11](https://user-images.githubusercontent.com/10371513/163043224-5b7ae0f4-4a08-48b7-9daf-c073f7710fb6.png)

**Comment by QuentinTournier40** [comment]
Hi,
I think I fixed that, tell me

**Comment by FlachyJoe** [comment]
It works, thank you.
